# Generated by Django 2.2 on 2020-08-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filma',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
