# Generated by Django 2.2 on 2020-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filma', '0002_filma_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filma',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
