# Generated by Django 2.2 on 2020-08-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filma', '0004_auto_20200811_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filma',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
