# Generated by Django 2.2 on 2020-08-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filma', '0007_auto_20200811_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='filma',
            name='imdb',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filma',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filma.Genre'),
        ),
    ]
