# Generated by Django 2.2 on 2020-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filma', '0008_auto_20200811_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_pic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
